### ISSUE TITLE
会出现滑块之后（不管成功与否）关不掉的情况，请问是什么原因？

### ISSUE THREAD

**Issue by luengwaiban** [01ly/TTBot#6]
会出现滑块之后（不管成功与否）关不掉的情况，请问是什么原因？

在scrapy中使用的，异常也捕获不到，就是会一直打开chrome...

**Comment by luengwaiban** [comment]
关键的滑块代码如下：
![image](https://user-images.githubusercontent.com/26041575/68742762-e8f5ba80-062b-11ea-803a-78c70dc85b69.png)

**Comment by 01ly** [comment]
你这个情况我知道，可以pull 一下，因为当时写这个很粗糙，当做示例而已，可以自己在代码里细化写。

**Comment by luengwaiban** [comment]
@01ly pull 一下？你有修复到这个问题了？还是说需要自己在源码里面修一下？

**Comment by luengwaiban** [comment]
@01ly 看到一段代码不知道喔有没有理解错，注释那里是我的理解
![image](https://user-images.githubusercontent.com/26041575/68923447-4e2ae680-07b9-11ea-9e51-52a29499083b.png)

**Comment by 01ly** [comment]
哈哈，回头挤时间修复，最近事儿多

**Comment by 01ly** [comment]
fixed
